name: build
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "target_branch_name=${{ github.head_ref || github.ref_name  }}" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - run: echo ${{ needs.setup.outputs.target_branch_name }}
