name: build

env:
  TARGET_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  JOB_CONDITION: github.event_name == 'workflow_dispatch'

on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    # if: ${{ env.JOB_CONDITION }} # cant't do this
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: '' # pass
    outputs:
      target_branch_name: ${{ github.head_ref || github.ref_name }}
  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - run: echo ${{ needs.setup.outputs.target_branch_name }}
      - run: echo "$TARGET_BRANCH_NAME"
